package com.junior.autoshop;

public class PhpConf {
    private final static String ip = "192.168.43.254";

    private final static String prefix = "https://" + ip + "/autoshop/";
    public final static String URL_CONNECTION = "connection.php";
    public final static String URL_LOGIN = prefix + "login.php";
    public final static String URL_REGISTER_CUSTOMER = prefix + "register_customer.php";
    public final static String URL_REGISTER_AUTOSHOP = prefix + "register_autoshop.php";
    public final static String URL_GET_PROFILE_AUTOSHOP = prefix + "get_profile_autoshop.php";
    public final static String URL_GET_PROFILE_CUSTOMER = prefix + "get_profile_customer.php";
    public final static String URL_UPDATE_PROFILE_AUTOSHOP = prefix + "update_profile_autoshop.php";
    public final static String URL_UPDATE_LOCATION_AUTOSHOP = prefix + "update_location_autoshop.php";
    public final static String URL_UPDATE_PICKUP_TIME = prefix + "update_pickup_time.php";
    public final static String URL_ADD_SERVICE_AUTOSHOP = prefix + "add_service_autoshop.php";
    public final static String URL_GET_SERVICE = prefix + "get_service.php";
    public final static String URL_DELETE_SERVICE_AUTOSHOP = prefix + "delete_service_autoshop.php";
    public final static String URL_GET_BOOKED_TRANS = prefix + "get_booked_trans.php";
    public final static String URL_GET_WORKING_SPACE = prefix + "get_workingspace_trans.php";
    public final static String URL_GET_TRANS_SERVICE = prefix + "get_trans_service.php";
    public final static String URL_GET_TRANS_COST = prefix + "get_trans_cost.php";
    public final static String URL_UPDATE_TRANS_PROGRESS = prefix + "update_trans_progress.php";
    public final static String URL_UPDATE_LOCATION_DELIVERY = prefix + "update_location_delivery.php";
    public final static String URL_ADD_TRANS_COST = prefix + "add_trans_cost.php";
    public final static String URL_DELETE_TRANS_COST = prefix + "delete_trans_cost.php";
    public final static String URL_CHANGE_STATUS = prefix + "change_status.php";
    public final static String URL_ACCEPT_TRANS = prefix + "accept_trans.php";
    public final static String URL_FINISH_TRANS = prefix + "finish_trans.php";
    public final static String URL_GET_WFP_TRANS = prefix + "get_wfp_trans.php";
    public final static String URL_GET_FINISHED_TRANS = prefix + "get_finished_trans.php";
    public final static String URL_GET_FINISHED_TRANS_AUTOSHOP = prefix + "get_finished_trans_autoshop.php";
    public final static String URL_UPDATE_PROFILE_CUSTOMER = prefix + "update_profile_customer.php";
    public final static String URL_DELETE_VEHICLE_CUSTOMER = prefix + "delete_vehicle_customer.php";
    public final static String URL_ADD_VEHICLE_CUSTOMER = prefix + "add_vehicle_customer.php";
    public final static String URL_GET_VEHICLE = prefix + "get_vehicle.php";
    public final static String URL_GET_NEARBY_AUTOSHOP = prefix + "get_nearby_autoshop.php";
    public final static String URL_CREATE_TRANS = prefix + "create_trans.php";
    public final static String URL_GET_SOS_AUTOSHOP = prefix + "get_sos_autoshop.php";
    public final static String URL_GET_ONGOING_TRANS = prefix + "get_ongoing_trans.php";
    public final static String URL_GET_ONGOING_DETAIL = prefix + "get_ongoing_detail.php";
    public final static String URL_CANCEL_TRANS = prefix + "cancel_trans.php";
    public final static String URL_GET_FAVORITE = prefix + "get_favorite.php";
    public final static String URL_GET_FAVORITE_LIST = prefix + "get_favorite_list.php";
    public final static String URL_GET_FAVORITE_LIST_SOS = prefix + "get_favorite_list_sos.php";
    public final static String URL_ADD_FAVORITE = prefix + "add_favorite.php";
    public final static String URL_DELETE_FAVORITE = prefix + "delete_favorite.php";
    public final static String URL_CHANGE_PICKUP_OPTION = prefix + "change_pickup_option.php";
    public final static String URL_GET_OCCUPIED_SPACE = prefix + "get_occupied_space.php";
    public final static String URL_UPLOAD_PAYMENT_PROOF = prefix + "update_payment_proof.php";
    public final static String URL_REISSUE = prefix + "reissue.php";
}
